-- Run this in the Supabase SQL Editor before deploying the closure-table code.
-- Closures are stored separately so closing/reopening a slot never overwrites a booking.

create table if not exists public.closures (
  id bigint generated by default as identity primary key,
  booking_date date not null,
  time_slot text not null,
  created_at timestamptz not null default now(),
  constraint closures_booking_date_time_slot_key unique (booking_date, time_slot),
  constraint closures_time_slot_not_empty check (length(trim(time_slot)) > 0)
);

create index if not exists closures_booking_date_idx
  on public.closures (booking_date);

-- Preserve currently active legacy closures while moving reads/writes to this table.
-- Do not delete or modify the source rows in bookings; some may contain prior booking data.
insert into public.closures (booking_date, time_slot)
select distinct booking_date, time_slot
from public.bookings
where status = 'closed'
  and deleted_at is null
  and booking_date is not null
  and time_slot is not null
on conflict (booking_date, time_slot) do nothing;

-- The application accesses this table through the server-side service role only.
alter table public.closures enable row level security;
